### ISSUE TITLE
Lightsaber open/close shouldn't have use animation

### ISSUE THREAD

**Issue by kaeptmblaubaer1000** [Parzivail-Modding-Team/StarWarsGalaxy#20]
**Describe the bug**
The lightsaber moves a bit while opening/closing it and this looks stupid because the lightsaber is in the hand and not a button a block away, where this animation makes sense.

**To Reproduce**
Steps to reproduce the behavior (example):
1. Take a lightsaber
2. Open it and look at the blade while it activates

**Expected behavior**
It opens/closes without any animation

**Screenshots**

**Please complete the following information:**
 - Mod Version [e.g. 1.3.0]: 0.0.5-51-g06f77cd
 - Minecraft Version [i.e. 1.7.10]: 1.7.10
 - Forge Version [e.g. 10.13.4.1558] 10.13.4.1558
 - Java Version [e.g. 8] 8u51 (from Mojang)

**Additional context**
Add any other context about the problem here. If you have other mods installed, please list them here.

**Comment by parzivail** [comment]
You must be looking at a block. This is default Minecraft behavior for held items when interacting with a block. Try this with other items to see what I mean. Regardless, I have changed the mechanism for opening and closing lightsabers to accommodate blocking with them.
